# Uncomment the lines below you want to change by removing the # in the beginning

devices([
   "iPhone 7 Plus",
   "iPhone 11 Pro Max",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (3rd generation)",
 ])

languages([
  "en-US",
])

scheme("PoshReVoEkranKopiilo")
clear_previous_screenshots(true)
