# Uncomment the lines below you want to change by removing the # in the beginning

devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 11",
   "iPhone 11 Pro",
   "iPhone 11 Pro Max",
   "iPad Pro (12.9-inch) (3rd generation)",
   "iPad Pro (9.7-inch)",
 ])

languages([
  "en-US",
])

scheme("PoshReVoEkranKopiilo")
clear_previous_screenshots(true)
